# Generated by Django 4.1.2 on 2022-11-21 21:48

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_missing', models.DateField(verbose_name='')),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('age_at_missing', models.IntegerField()),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
